"""Clearly labeled, static sample data for the prototype experience."""

SIGNALS = [
    {
        "id": "ai-inference-efficiency",
        "title": "Inference efficiency becomes a competitive wedge for AI platforms",
        "summary": "Sample signal: product teams are increasingly comparing deployment cost and latency alongside model quality as they move pilots into production.",
        "category": "AI BREAKTHROUGH",
        "feed_category": "AI Breakthroughs",
        "topic": "AI",
        "source": "DOST ALPHA sample desk",
        "published": "2 hours ago",
        "reading_minutes": 4,
        "impact_score": 91,
        "signal_score": 88,
        "confidence_score": 84,
        "velocity": "Accelerating",
        "business_impact": "High",
        "sentiment": "Positive",
        "url": "https://example.com/",
    },
    {
        "id": "startup-agent-workflows",
        "title": "Vertical AI agents shift from demos toward accountable workflows",
        "summary": "Sample signal: adoption narratives are moving toward measurable task completion, audit trails, and human review in narrow industry workflows.",
        "category": "STARTUP WATCH",
        "feed_category": "Startup Watch",
        "topic": "Startups",
        "source": "DOST ALPHA sample desk",
        "published": "5 hours ago",
        "reading_minutes": 6,
        "impact_score": 86,
        "signal_score": 82,
        "confidence_score": 79,
        "velocity": "Rising",
        "business_impact": "High",
        "sentiment": "Positive",
        "url": "https://example.com/",
    },
    {
        "id": "search-answer-engines",
        "title": "Answer engines are changing the shape of high-intent discovery",
        "summary": "Sample signal: brands are testing how structured, authoritative answers surface across conversational discovery products.",
        "category": "MARKET MOVERS",
        "feed_category": "Market Movers",
        "topic": "SEO",
        "source": "DOST ALPHA sample desk",
        "published": "Yesterday",
        "reading_minutes": 5,
        "impact_score": 82,
        "signal_score": 77,
        "confidence_score": 76,
        "velocity": "Rising",
        "business_impact": "Medium",
        "sentiment": "Neutral",
        "url": "https://example.com/",
    },
    {
        "id": "open-source-model-stack",
        "title": "Open model tooling is widening the deployment choice set",
        "summary": "Sample signal: more capable open models and serving tools may make workload-specific deployment economics more attractive.",
        "category": "EMERGING TRENDS",
        "feed_category": "Emerging Trends",
        "topic": "Technology",
        "source": "DOST ALPHA sample desk",
        "published": "Yesterday",
        "reading_minutes": 3,
        "impact_score": 74,
        "signal_score": 72,
        "confidence_score": 73,
        "velocity": "Stable",
        "business_impact": "Medium",
        "sentiment": "Positive",
        "url": "https://example.com/",
    },
    {
        "id": "enterprise-security-review",
        "title": "Enterprise AI rollouts put governance controls under scrutiny",
        "summary": "Sample signal: buyers are asking for permissioning, auditability, and data boundaries before expanding internal AI access.",
        "category": "CRITICAL SIGNAL",
        "feed_category": "Critical Signals",
        "topic": "AI",
        "source": "DOST ALPHA sample desk",
        "published": "2 days ago",
        "reading_minutes": 7,
        "impact_score": 89,
        "signal_score": 80,
        "confidence_score": 87,
        "velocity": "Accelerating",
        "business_impact": "Critical",
        "sentiment": "Negative",
        "url": "https://example.com/",
    },
    {
        "id": "market-opportunity-data",
        "title": "Specialized data operations surface as a potential AI opportunity",
        "summary": "Sample signal: data quality, evaluation, and governance work may become a durable service layer as more teams operationalize AI.",
        "category": "HIDDEN OPPORTUNITY",
        "feed_category": "Hidden Opportunities",
        "topic": "Business",
        "source": "DOST ALPHA sample desk",
        "published": "3 days ago",
        "reading_minutes": 5,
        "impact_score": 78,
        "signal_score": 75,
        "confidence_score": 70,
        "velocity": "Rising",
        "business_impact": "High",
        "sentiment": "Positive",
        "url": "https://example.com/",
    },
]

TREND_RADAR = {
    "AI": 91,
    "Business": 68,
    "Finance": 56,
    "Technology": 81,
    "Startups": 74,
    "Marketing": 62,
    "Cybersecurity": 70,
    "Healthcare": 49,
    "SEO": 77,
}
